name: Markdown Link Check

on:
  pull_request:
    paths:
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Changed Markdown Files
        id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            **/*.md

      - name: Write changed files list
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: printf '%s\n' $CHANGED_FILES > "$RUNNER_TEMP/changed-md-files.txt"

      - name: Run Link Checker
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: --verbose --no-progress --exclude-loopback ${{ steps.changed-files.outputs.all_changed_files }}
          fail: true